### PR TITLE
Standalone samples and sample creation form

### PR DESCRIPTION
**Pull request by Espurna**
This functionality has not been finished yet, but I created the PR now in order to allow viewers to start their evaluation since it involves a lot of different files.

Apart of creating a new functionality, this PR also include some code improvement related with Sample-AnalysisRequest relation and Creation forms views.

## Description of the issue/feature this PR addresses

System should have a clear and simple sample registration process.

An “Add” button for the creation of a new Sample has to be added in Samples lists. Once the button is clicked, the user will be redirected to a form for the creation of a Sample. This form will be quite similar to the one already available in SENAITE.CORE (used for the creation of Analysis Requests), but will not prompt the user to fill the information about analyses, like specifications, templates or tests to be carried out.

Once the form is filled, the new Sample will be saved and transitioned to  “sample_due” (or “to_be_sampled”) depending if the sampling workflow is enabled in Bika Setup.

Samples may also be rejected on receipt thus we need to include ability to reject in creation.

In the new Sample Creation form, the same functionality for rejection in creation, that is already available in the Analysis Request Add form, will be included. Once the user selects to reject the Sample, a popup form for the user to set the reason of rejection (with a free-text too) will be displayed. Note that in Bika Setup the user can set which are the rejection reasons to be displayed in the popup's selection list. The same reasons will be used for the Sample rejection at creation.

## Current behavior before PR

Samples can only be created on analysis request creation.

## Desired behavior after PR is merged

The creation of Samples without the need of creating an Analysis Request.

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

### CODE REVIEW

**Comment by ramonski** [comment]
Hi @Espurna, I don't see the need to create a new AR Add view for that purpose, because that view can handle this case as well.
As far as I can see the only thing that needs to be changed is that not all fields get displayed for Samples and that the submit action is different.

Remember to avoid to to repeat code, and currently there is too much duplication...

**Comment by Espurna** [comment]
Hi @ramonski this PR doesn't create a new AR Add form, it is creating a **Sample Add/Register** form. 

Please, don't be afraid of this PR, I am not planning to remove the "not ready for merge" label until I have written tests and checked each LIMS feature very very carefully (inlcuding health).

I opened the PR in order to allow reviewers to take their time to review its code without rush.

Let me excuse myself before rejecting this PR for being big :) ::

So far Samples and ARs are sharing a lot of unnecessary fields and confuse users and coders but it doesn't need to be the same in future versions. From a conceptual point of view a question could be: why Analysis Requests have a DateSampled/SamplingDate/ScheduledSampling/Sampler (among others) fields? Shouldn't they live in Sample object only?

This PR would allow users to create/register samples, receive them or retract them without forcing users to create an Analysis Request for it.

About duplicate code, I took care of creating "base" classes for sample and analysis request add forms to avoid code duplication. But I duplicated JS/coffee and HTML since I thought it would be easier and less harmful to keep that logic separated. I will appreciate any suggestion to improve code.

From your comment, I understand that you are suggesting to use the AR Add logic to register a sample? Actually this is what I have done, taking advantage of the current AR Add logic and moving shared logic to https://github.com/senaite/senaite.core/pull/579/files#diff-dbe3a162cc31a9877e440e3a3cf7acfbR26

This would be the first step to make samples the "core" object in SENAITE.

**Comment by Espurna** [comment]
Take ideas from https://github.com/senaite/senaite.core/pull/329

**Comment by xispa** [comment]
Allowing the user to create Samples w/o the need of creating an Analysis Requests is a desired functionality that some labs have been requesting from time to time. Regardless of these requests, the truth is that Analysis Request and Sample records generate a lot of confusion to end users. 

While in some labs, the many-to-one relationship between Analysis Request and Sample fits well, in a lot of cases, this is not what the lab expects. Rather, they expect to an Analysis Request to be able to include more than one Sample (many-to-many): eg., a client requests an Analysis Request for 3 Samples at once and expects the results report to include all 3 samples. A long time ago, the [New Results Template, COA. Multiple ARs in columns #1652](https://github.com/bikalims/bika.lims/pull/1652) was introduced to solve this caveat, allowing the user to generate reports for multiple ARs.

There are plenty of use cases in which one would like to be able to create Samples without the need of creating Analysis Requests. I've always seen the Analysis Request as an "artifact" to submit Samples to the lab and request analyses against them, nothing more. Thus, thinking about an AR as the central object of the system is a flaw imo. For me, Sample, Worksheet and, especially, Analysis are the central entities of the system. Think about it, most of all information during AR registration belongs to either the Sample or the Analyses, and only a small fraction of the data introduced belongs to the Analysis Request. In addition, I see Worksheet as the fundamental piece for managing and plannning the work to be done in the lab (in fact, I've always thought that setting the results for analyses directly in AR manage results view is a bad practice). Maybe it gets clear when we talk about workflows: for me, it does not make sense that ARs and Analyses stick to the `sample_workflow`, it should apply to `Sample` only and the rest of objects have their own workflow definition, regardless of the Sample state and its allowed transitions. With this reasoning we see again that an AR is only an artifact.

All this being said, this is an important addition that unfortunately affects some nuts from AR and AR Add (in most cases because of `ar_num` var name). Thus, this PR must include exhaustive tests to guarantee that both the AR Add and Sample Add forms work as expected. Functional thorough testing is also required.

**Comment by ramonski** [comment]
Thanks @xispa and I completely share your point of view regarding the need to have standalone Samples in the LIMS with the ability to create ARs optionally.

In fact, a customer of mine has this common use-case:

They receive Samples w/o any description or further information, neither _who_ send the sample to them, nor _what_ they need to analyze.

So they want to register a Sample in the LIMS (probably with a photo), until they figured out what they have to do or who send that sample to them. Then they want to eventually create an AR for it.

Therefore, I completely support that approach and I'm actually not afraid of this change, even if it might have appeared like this in my first comment.

The only thing I want to ensure is that this central AR Add form is extended correctly right from the beginning, so that ARs or Samples can get added w/o unnecessary code duplication, and that use-cases like mass-editing or AR/Sample import are considered right from the beginning, with as much reusable code components as possible and not too much code splitting.

Who knows if this whole thing get refactored somewhen into a modern Reach JS component, therefore I would like to keep the JS duplication as less as possible.

**Pull request closed without merging**
