### PR TITLE
Date Sampled in Samples listing requires a datetime picker

### PR DESCRIPTION
**Pull request by mikejmets**
## Description of the issue/feature this PR addresses

Linked issue: https://github.com/senaite/senaite.core/issues/1787

## Current behavior before PR
Date Sampled in Samples listing is a text input field

## Desired behavior after PR is merged
Date Sampled in Samples listing has a datetime picker

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

### CODE REVIEW

**Comment by mikejmets** [comment]
The other half of this equation is https://github.com/mikejmets/senaite.app.listing/tree/MM-datetime but I cannot create an issue or pull request for it. Please advise.

**Comment by ramonski** [comment]
We disabled issue tracking in add-ons, but PRs should be possible.
Does creating a PR work for you?

**Comment by mikejmets** [comment]
Created associated PR https://github.com/senaite/senaite.app.listing/pull/56

**Comment by mikejmets** [comment]
I cannot seem to find any samples in the Samples listing in browser contents. Any ideas where I'm going wrong?

**Comment by ramonski** [comment]
Hi Mike,
the Zope Testbrowser does not support JavaScript.
Maybe you can work around by displaying the JSON folderitems with `view/folderitems`

**Comment by mikejmets** [comment]
Thanks @ramonski, your idea worked well. Note that I enabled SamplingWorkflow and the existing tests in Listing still passed.

**Review by ramonski — APPROVED** [review]

**Pull request merged**
