### PR TITLE
Fix analysis results derived from calculations not being formatted (#2355)

### PR DESCRIPTION
**Pull request by luthando5**
## Description of the issue/feature this PR addresses

Linked issue: https://github.com/senaite/senaite.core/issues/2355

## Current behavior before PR

The result of the analysis service does not have any formatting that is particular to the analysis service.

## Desired behavior after PR is merged

The result of the analysis service is formatted according to the attributes of the analysis service like precision.

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

### CODE REVIEW

**Comment by ramonski** [comment]
Hi @luthando5,
there are still failing tests in this PR, see:
https://github.com/senaite/senaite.core/actions/runs/5939052301/job/16104695677?pr=2356
Once the tests pass, we can merge it into the core.
Thanks!

**Comment by luthando5** [comment]
Thanks @ramonski I appreciate the message. I'm on it!

**Comment by luthando5** [comment]
@ramonski I've closed the issue as I can't reproduce it anymore :)

**Comment by ramonski** [comment]
Hi @luthando5,
Thanks for your feedback!
Did the issue disappear with an update to the latest SENAITE version or are you still on the same version?

**Comment by luthando5** [comment]
@ramonski I'm on the latest SENAITE version now and I can't reproduce it. There might be a chance that I wasn't creating new samples when testing the results formatting i.e I was updating the Analysis Service but not testing on new samples every time an update to the AS was made. Could be either of the two.

**Pull request closed without merging**
