### PR TITLE
Allow to hide actions menu by using new marker interface IHideActionsMenu

### PR DESCRIPTION
**Pull request by xispa**
**IMPORTANT: DO NOT MERGE INTO 2.x. Counterpart in there: https://github.com/senaite/senaite.core/commit/e03ecaa1257efdf6e3b924ea915faa1b777df85b**

## Description of the issue/feature this PR addresses

This Pull Requests adds the marker interface `IHideActionsMenu`, so the system won't render the action menu display list for those contents implementing this marker interface. This Pull Request also resolves https://github.com/senaite/senaite.core/issues/1325

## Current behavior before PR

No easy way to hide the actions menu for a given type

## Desired behavior after PR is merged

Easy way to hide actions menu for a given type

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

### CODE REVIEW

**Comment by ramonski** [comment]
How shall we continue with `2.x` if we cannot merge `master` anymore starting with this PR? As far as I know it is not possible to skip/ignore a specific commit on merge...

**Comment by xispa** [comment]
> How shall we continue with `2.x` if we cannot merge `master` anymore starting with this PR? As far as I know it is not possible to skip/ignore a specific commit on merge...

Ummm, I think we have two options here:
- Do cherry-picks from now onwards
- Revert commits https://github.com/senaite/senaite.core/commit/e03ecaa1257efdf6e3b924ea915faa1b777df85b and https://github.com/senaite/senaite.core/commit/f7f5e96b716c4156cdff1ec8a95ad8f3c9c7e331 from 2.x and merge later this one into 2.x. The only difference is that in 2.x, `IHideActionMenu` will live in `bika.lims.interfaces` (instead of `senaite.core.interfaces`)

**Comment by ramonski** [comment]
I think cherry picking is not an option. I would suggest to merge and change the code in 2.x accordingly.

**Comment by xispa** [comment]
> I think cherry picking is not an option. I would suggest to merge and change the code in 2.x accordingly.

Ok, do you want me to revert those two commits from 2.x?

**Comment by xispa** [comment]
Well, is not necessary to revert the commits. Just merge and fix the conflicts (remove the interface from `bika.lims.interfaces` in 2.x and fix the import for `ReportsFolder`

**Comment by ramonski** [comment]
No, I think it’s fine when we do the changes afterwards manually in 2.x and push directly

**Pull request merged**
