### PR TITLE
Users without privileges can create reports

### PR DESCRIPTION
**Pull request by rockfruit**
## Description of the issue/feature this PR addresses

Linked issue: https://github.com/senaite/senaite.core/issues/896

## Current behavior before PR

Reports tab is visible and permissions on folder are granted to Member and/or Owner roles.

## Desired behavior after PR is merged

Only Manager and LabManager have access.

A user without permission to any of the top-bar actions, doesn't see a top-bar at all - I think it's nice

I tried to use an expression in the view instead of adding another permission just for this,
but in the end this way just seemed less hacky for something so silly as this.

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

### CODE REVIEW

**Comment by xispa** [comment]
@ramonski , having a workflow for reports would be perfect, but in my opinion, it would be better to not mix things, open a new PR for that and leave this PR as it is.

**Comment by xispa** [comment]
Aa, now I see. A new permision `ManageReports` is created in this PR to solve the issue. Agree @ramonski , better to create an own workflow for Reports. Labeling this one with `changes-requested`

**Comment by rockfruit** [comment]
> Aa, now I see. A new permision ManageReports is created in this PR to solve the issue. Agree @ramonski , better to create an own workflow for Reports. Labeling this one with changes-requested

The permission was created to control visibility/access to the portal_tabs 'reports' action.  I don't know another way.  I agree regarding the creation of a workflow for reports, although I'm uncertain how it affects the requirement for this permission.

**Comment by rockfruit** [comment]
I'm talking of the action here: https://github.com/senaite/senaite.core/blob/7679a52facb150aaf63eb0b3b08119f10d51e9ec/bika/lims/profiles/default/actions.xml#L148 - It has no relation to workflow permissions.

Could we move this item to a normal 'nav' position, eg, where it's backed by a real object in the database which can have permissions?  eg, a "reports" folder object on the root?

**Comment by ramonski** [comment]
## TODO

Only apply the new WF to the report folder to fix that Users without privileges can create reports

**Comment by xispa** [comment]
Superseded by https://github.com/senaite/senaite.core/pull/1237

**Pull request closed without merging**
