### PR TITLE
Migrate SubGroups to DX

### PR DESCRIPTION
**Pull request by toropok**
## Description of the issue/feature this PR addresses

This PR migrates the AT based Sub Groups (SubGroup) to Dexterity

## Current behavior before PR

Sub Groups are based on the Archetype Framework

## Desired behavior after PR is merged

Sub Groups are based on the Dexterity Framework

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

### CODE REVIEW

**Comment by toropok** [comment]
@xispa ready for review

**Review by ramonski — COMMENTED** [review]
Hi @toropok,
works well, many thanks!
Can you just resolve the conflicts, then this one can be merged next.

**Comment by toropok** [comment]
> Hi @toropok, works well, many thanks! Can you just resolve the conflicts, then this one can be merged next.

@ramonski 

hi :) done. Ready to go for next one

**Review by ramonski — APPROVED** [review]
Thanks Leo!

**Comment by toropok** [comment]
@ramonski 

I'm very sorry for that, but I found my typo in this PR. What is right way to fix it? 

it is located here:
https://github.com/senaite/senaite.core/blob/976c3f8fbacbb12d72d2d7ed2920329526767b61/src/senaite/core/profiles/default/types/SubGroup.xml#L14

need just replace factory `ContainerType`->`SubGroup`

can we just correct it (hope nobody get it yet) or need to issue patch with remigration?

P.S.: I dont know how I missed this typo due we test everything locally first.

**Comment by ramonski** [comment]
Hi @toropok,
no worries, I didn't catch that error either during review.
Just make a new PR that corrects this issue and put a proper description that it corrects this issue from #2545.
There is no need for a separate changelog line.
Thanks for your work and efforts, much appreciated!

**Pull request merged**
