### PR TITLE
More informative progress of the sample analyses states

### PR DESCRIPTION
**Pull request by ramonski**
## Description of the issue/feature this PR addresses

This PR improves the "Number of Analyses" column info in the sample listing:

## Current behavior before PR

Only verified and total number was displayed

## Desired behavior after PR is merged

Number of analyses are displayed as:
Open / To be verified / Verified / Total 

An info is displayed when moving the mouse over the number and the same color codes as the WF states are used.
--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

### CODE REVIEW

**Review by xispa — COMMENTED** [review]
I've just practiced with same idea but using bootstrap's multiple bar and looks like this:

Captura de 2024-02-11 22-17-09

with an snippet like this:

```html
<div class="progress">
  <div class="progress-bar" role="progressbar" style="width: 50%;background-color: #6c757d;" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100">5</div>
  <div class="progress-bar" role="progressbar" style="width: 20%;background-color: #18ffff;color: black;" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">2</div>
  <div class="progress-bar" role="progressbar" style="width: 30%;background-color: #0091ea;" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100" >3</div>
</div>
```

What do you think?

**Comment by ramonski** [comment]
I would rather stick to the distinct numbers instead of a bar with a variable width to have it more intuitive for the user. In the progress bar approach (although I like the design), it would be also difficult to display if e.g. 10/10 verified, but not published. Is the published bar then invisible? Does it show half/half? Do the other bars disappear? Therefore, I guess we should keep it as simple as possible.

**Comment by ramonski** [comment]
I guess a usable solution could be to use the progress bar styling and apply `25%` per part. Would you prefer this styling?

**Comment by xispa** [comment]
> I guess a usable solution could be to use the progress bar styling and apply `25%` per part. Would you prefer this styling?

I like it more than simply the numbers, yes. At least it becomes more "easy" to get the point on a quick look

**Comment by ramonski** [comment]
Ok, then I'll change it to this styling.

**Comment by ramonski** [comment]
I changed it now to the progress bar style and chose the same width as our current %-progress:



The mousover help text is still possible

**Comment by ramonski** [comment]
I tested the brown "sample received" background for the first number, but it looked a bit sh***y

**Review by xispa — APPROVED** [review]

**Pull request merged**
