### PR TITLE
Better handling of RemarksField and friendly display

### PR DESCRIPTION
**Pull request by xispa**
## Description of the issue/feature this PR addresses

Remarks field is a bit wonky, especially because of how handles and displays the text. This Pull Request improves the RemarksField as well as it's look&feel (see screenshot below).

Remarks are now stored in a list (a `RemarksHistory` object) made of dicts (`RemarksHistoryRecord` objects), that allows easy access to remark entries and metadata as well (user id, user name, etc). It opens the possibility to add more keys in the `RemarksHistoryRecord` dict to handle future behaviors (e.g. pin remarks, choose those to be printed in results report, etc.)

Captura de 2019-12-23 00-26-37

## Current behavior before PR

The way RemarksField works is wonky

## Desired behavior after PR is merged

RemarksField becomes more flexible

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

### CODE REVIEW

**Comment by ramonski** [comment]
It also seems that the timestamp for new remarks is missing:

Remarks Test

Is there any chance to migrate existing remarks to the new format?

Also just an idea: How about storing that whole thing in JSON format?

**Comment by ramonski** [comment]
Sorry, the timestamp is now displayed after a full reload, but old comments get the same timestamp as the new ones:



Also I would rather display the full date instead of the friendly date and do the conversion in JavaScript with [moment](https://momentjs.com)

**Comment by xispa** [comment]
> Also I would rather display the full date instead of the friendly date

Done

> Is there any chance to migrate existing remarks to the new format?

Can be done, but since the remarks is already handling legacy values without having to walk-through all objects in an endless upgrade step, I thought that was not worth.

> Also just an idea: How about storing that whole thing in JSON format?

I did store the value jsonified at the beginning:

https://github.com/senaite/senaite.core/pull/1495/commits/0718a9b431db07a94a3a2f827a8cc6ded80ed84a#diff-ff77314d577c3d0d3aca8ee30f1ff8a9L107

but I thought it was making the thing more complex without providing any benefits.

> Fails for Unicode Remarks with the following Traceback:

Umm, this comes from the markdown library. I tested the RemarksField using `html_content` instead of `markdown_content` and was warking properly. This was my last commit and I did not test it thoroughly. Going to take a look

**Comment by ramonski** [comment]
Clicking on the "Add Remarks" Button when the field is empty causes this traceback:

```
  File "Products.ZCatalog-2.13.30-py2.7.egg/Products/ZCatalog/Catalog.py", line 303, in updateMetadata
    if data.get(index, 0) != newDataRecord:
  File "senaite.core/bika/lims/browser/fields/remarksfield.py", line 56, in __eq__
    return super(list, self).__eq__(y)
AttributeError: 'super' object has no attribute '__eq__'
```

After this, the field does no longer accept any values.

**Comment by xispa** [comment]
@ramonski I've tried to reproduce the error w/o success. Nevertheless, I've pushed this change https://github.com/senaite/senaite.core/pull/1495/commits/30e43ebdcb65ad9b3b724608acdf68cd2bdc2233 (`super` was not correctly called) that I think should fix the issue you are experiencing

**Comment by ramonski** [comment]
Ok, the error does not occur anymore, but leaving the field empty and pressing "Add Remarks" repeats always the last message.

**Comment by ramonski** [comment]
It seems like the values are not stored and reloading the page flushes the duplicates

**Comment by xispa** [comment]
Umm, are you sure you refreshed Ctrl+F5? I don't have these issues.

**Comment by ramonski** [comment]
Yes, getting this behavior in Chrome and FireFox with disabled Cache. I'm just pressing "Add Remarks" in a Sample which contains already at least one Remark.

**Comment by xispa** [comment]
Ok. Will try again to reproduce the issue

**Comment by ramonski** [comment]
Doing this in a new Sample w/o Remarks produces this JS Error and an endless Spinner:

wmKSS-20-0022-R01 — BECHEM LIMS 2020-01-09 09-43-54

**Comment by ramonski** [comment]
Here the behavior when pressing "Add Remarks" w/o Comment in a Sample with existing Remarks:

**Comment by xispa** [comment]
I think is working fine now, except that the styling of remarks fields in places where the form is automatically rendered by AT (e.g. for setup content types such as `Analysis Profile`) is missing because of this change: https://github.com/senaite/senaite.core/pull/1495/commits/cd5b73486080a5680d6cbe5fa0ddb12a90119771#diff-08f153d902254658e1293551c2475c89

Without the previous commit and adding the following property in `remarkswidget.py`:

```
        'helper_css': (
            "bika_widgets/remarkswidget.css",),
```

the remarks styling in e.g. Analysis Profile (both in view and edit), would look like this:

Captura de 2020-01-11 23-48-14

Now it looks like follows:

Captura de 2020-01-11 23-52-52

**Comment by xispa** [comment]
Also, I feel the sort order from newest to oldest is quite confusing. I know it was like this before, but still...

**Comment by ramonski** [comment]
Hmm, I've seen that in view-mode the class `ArchetypesRemarksWidget` was absent, that's why I did the change. Shall we remove these Remarks fields in the Setup Items? I think they are misplaced there anyway...

**Comment by xispa** [comment]
> Or maybe we can use a simple text widget for the remarks in setup items? I've seen that this is the case for Analysis Services.

Agree, I don't think such remarks widget makes sense in setup items. A simple text widget would work, indeed.

**Pull request merged**
