### PR TITLE
Tabbed content view

### PR DESCRIPTION
**Pull request by ramonski**
## Description of the issue/feature this PR addresses

This PR improves the content view to show the contents within tabs like in the edit view and horizontal instead of stacked.

## Current behavior before PR

All values are shown stacked in one page:

Micro-Bio check — SENAITE LIMS 2024-11-20 3 PM-09-20

## Desired behavior after PR is merged

Items are shown horizontal in tabs:

Micro-Bio check — SENAITE LIMS 2024-11-20 3 PM-08-29

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

### CODE REVIEW

**Review by xispa — CHANGES_REQUESTED** [review]
Field descriptions are not displayed:

Captura de 2024-11-22 12-42-56

**Comment by ramonski** [comment]
> Field descriptions are not displayed:
> 
> Captura de 2024-11-22 12-42-56

Actually this was by purpose😄
IMO these make only sense in edit mode. What is your opinion?

**Comment by xispa** [comment]
> Actually this was by purpose😄 IMO these make only sense in edit mode. What is your opinion?

I see... a lot of descriptions do not explain what that field does or is about, but a *call-to-action*. For instance, for the field "Preferred Instrument", one might expect something like:

*The preferred instrument will be assign by default to analyses when this worksheet template is used*. 

However, the description of the field is a *call-to-action*:

*Select the preferred instrument*

Aarggggg..... A pity to loose the explanations about the fields in the view.... See for instance the description of the field "Maximum holding time" we added recently in services: https://github.com/senaite/senaite.core/pull/2624/files#diff-4b1e4865f41cae407b6d57d7a4f4d54ec094b2b47f16ff0be7257d94c7f5c3ecR379

*This service will not appear for selection on the sample registration form if the elapsed time since sample collection exceeds the holding time limit. Exceeding this time limit may result in unreliable or compromised data, as the integrity of the sample can degrade over time. Consequently, any results obtained after this period may not accurately reflect the sample's true composition, impacting data validity. Note: This setting does not affect the test's availability in the 'Manage Analyses' view.*

I think is cool to have it in the view, cause it explains a lot about its behavior.

I would keep the descriptions and keep this in mind for future PRs and revisit existing descriptions. If it does not look good, maybe with an informative tooltip?

**Comment by ramonski** [comment]
> I would keep the descriptions and keep this in mind for future PRs and revisit existing descriptions. If it does not look good, maybe with an informative tooltip?

Descriptions are now displays as tooltips on the label:

**Review by xispa — APPROVED** [review]
Excellent, thanks!

**Pull request merged**
