### PR TITLE
Allow (Multi-)Attachment upload available in AR Add

### PR DESCRIPTION
**Pull request by ramonski**
## Description of the issue/feature this PR addresses

Linked issue: https://github.com/senaite/senaite.core/issues/804

## Current behavior before PR

No file upload possible during AR Add

## Desired behavior after PR is merged

Multi File upload possible during AR Add.
All Files are stored as AR attachments.

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

### CODE REVIEW

**Comment by ramonski** [comment]
Hi Jordi, just see the first commit for the actual change (skip the last typo, I fixed it in the third commit;)).

Note: The actual "magic" was already in place in AR Add: https://github.com/senaite/senaite.core/blob/master/bika/lims/browser/analysisrequest/add2.py#L1703

**Review by xispa — CHANGES_REQUESTED** [review]
Got this:

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module bika.lims.browser.analysisrequest.add2, line 46, in decorator
  Module bika.lims.browser.analysisrequest.add2, line 843, in __call__
  Module bika.lims.browser.analysisrequest.add2, line 1831, in ajax_submit
  Module Products.Archetypes.BaseObject, line 636, in processForm
  Module bika.lims.content.attachment, line 131, in _renameAfterCreation
  Module bika.lims.idserver, line 425, in renameAfterCreation
  Module plone.folder.ordered, line 193, in manage_renameObject
  Module OFS.CopySupport, line 358, in manage_renameObject
  Module Products.CMFCore.PortalFolder, line 421, in _verifyObjectPaste
ValueError: Disallowed subobject type: Attachment
```

**Comment by xispa** [comment]
I tried with an instance I setup from scratch last week and I got the error above. But now I tried with another instance and it worked. I need to figure out what is going on here before accepting this one. Assigning this one to me.

**Comment by xispa** [comment]
I tried again this PR three days ago with a non-fresh install (different from the previous one I used the first time) and I got the same traceback. Got no time to go in detail though, but in my TODO list still

**Comment by ramonski** [comment]
Maybe that's the reason why Attachments are not allowed:
https://github.com/senaite/senaite.core/blob/master/bika/lims/profiles/default/types/AnalysisRequest.xml#L17

**Comment by ramonski** [comment]
Should work now and I removed the "Not Ready" Label again;)

**Review by xispa — APPROVED** [review]
Works pretty well now, thanks!

**Pull request merged**
