### PR TITLE
Migrate AttachmentTypes to DX

### PR DESCRIPTION
**Pull request by toropok**
## Description of the issue/feature this PR addresses

This PR migrates the AT based Attachment Types to Dexterity

## Current behavior before PR

Attachment Types are based on the Archetype Framework

## Desired behavior after PR is merged

Attachment Types are based on the Dexterity Framework

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

### CODE REVIEW

**Comment by toropok** [comment]
@ramonski please review

**Comment by ramonski** [comment]
Currently, the migration fails with this branch active and trying to run 2636 → 2637:

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 176, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 385, in publish_module
  Module ZPublisher.WSGIPublisher, line 288, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module Products.GenericSetup.tool, line 1135, in manage_doUpgrades
  Module Products.GenericSetup.upgrade, line 185, in doStep
  Module senaite.core.upgrade, line 39, in wrap_func_args
  Module senaite.core.upgrade.v02_06_000, line 1539, in move_instrumentlocations
  Module Products.GenericSetup.tool, line 375, in runImportStepFromProfile
  Module Products.GenericSetup.tool, line 1323, in _doRunImportStep
   - __traceback_info__: typeinfo
  Module Products.CMFCore.exportimport.typeinfo, line 222, in importTypesTool
  Module Products.GenericSetup.utils, line 933, in importObjects
   - __traceback_info__: portal_types
  Module Products.GenericSetup.utils, line 929, in importObjects
   - __traceback_info__: types/AttachmentType
  Module Products.GenericSetup.utils, line 530, in _importBody
  Module Products.CMFCore.exportimport.typeinfo, line 61, in _importNode
  Module Products.GenericSetup.utils, line 762, in _initProperties
ValueError: undefined property 'add_permission'
```

I could imagine, that we have to run this line in these importers , before importing `typeinfo` and `workflow`:

```
    # ensure old AT types are flushed first
    remove_at_portal_types(tool)
```


Actually, I guess it is not required to run these steps in the "move" migrators, because the types are already DX 🤔

**Comment by ramonski** [comment]
Ok, making it short.
Can you please remove these lines from the "move" migrators coming before:

```diff
-    # run required import steps
-    tool.runImportStepFromProfile(profile, "typeinfo")
-    tool.runImportStepFromProfile(profile, "workflow")
```

They are not needed and cause the error shown above.

**Comment by toropok** [comment]
> Ok, making it short. Can you please remove these lines from the "move" migrators coming before:
> 
> ```diff
> -    # run required import steps
> -    tool.runImportStepFromProfile(profile, "typeinfo")
> -    tool.runImportStepFromProfile(profile, "workflow")
> ```
> 
> They are not needed and cause the error shown above.

@ramonski thanks! done

**Review by ramonski — APPROVED** [review]

**Comment by ramonski** [comment]
Thanks, works like a charm now!

**Pull request merged**
