### PR TITLE
Fix reject report to fully conform with the ISO standard

### PR DESCRIPTION
**Pull request by xispa**
## Description of the issue/feature this PR addresses

This Pull Request ensures the rejection report fully conforms with ISO standard by:

- including the date and time when the rejection of the sample/specimen was done
- including the full name of the person who rejected the sample/specimen
- including the signature of the person who rejected the sample/specimen
- including the full names of the lab personnel responsible of the sample
- including the signatures of the lab personnel responsible of the sample

It also ports the reject samples view to `senaite` namespace

## Current behavior before PR

Full names, datetime and signatures not present in rejection report

## Desired behavior after PR is merged

Full names, datetime and signatures are present in rejection report

--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

### CODE REVIEW

**Comment by ramonski** [comment]
Hi Jordi,
I'm getting this traceback when rejecting as `admin` user (i.e. a no `contact`/`labcontact` linked user):

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 176, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 385, in publish_module
  Module ZPublisher.WSGIPublisher, line 288, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module senaite.core.browser.samples.rejection.reject_samples, line 107, in __call__
  Module bika.lims.utils.analysisrequest, line 561, in do_rejection
  Module bika.lims.utils.analysisrequest, line 589, in get_rejection_pdf
  Module senaite.core.browser.samples.rejection.report, line 77, in to_pdf
  Module Products.Five.browser.pagetemplatefile, line 126, in __call__
  Module Products.Five.browser.pagetemplatefile, line 61, in __call__
  Module zope.pagetemplate.pagetemplate, line 135, in pt_render
  Module Products.PageTemplates.engine, line 378, in __call__
  Module z3c.pt.pagetemplate, line 176, in render
  Module chameleon.zpt.template, line 302, in render
  Module chameleon.template, line 215, in render
  Module chameleon.template, line 192, in render
  Module b05a995bf480bb598b35d63405c3c54f, line 1621, in render
  Module zope.tales.expressions, line 250, in __call__
  Module Products.PageTemplates.Expressions, line 217, in _eval
  Module zope.tales.expressions, line 153, in _eval
  Module Products.PageTemplates.Expressions, line 134, in trustedBoboAwareZopeTraverse
  Module zope.traversing.adapters, line 156, in traversePathElement
   - __traceback_info__: ({}, 'signature')
  Module zope.traversing.adapters, line 61, in traverse
   - __traceback_info__: ({}, 'signature', [])
LocationError: ({}, 'signature')

 - Expression: "member/signature"
 - Filename:   ... /browser/samples/rejection/templates/rejection_report.pt
 - Location:   (line 167: col 54)
 - Source:     ... ignature" tal:condition="member/signature">
                                            ^^^^^^^^^^^^^^^^
 - Arguments:  reasons: ['Sample volume not OK']
               modules: <Products.PageTemplates.ZRPythonExpr._SecureModuleImporter object at 0x102801b10>
               labreasons: ['Temperature not OK', 'Sample volume not OK', 'Sample container damaged']
               ar: <AnalysisRequest at /senaite/clients/client-6/24-533a-0069>
               attrs: {u'class': u'signature'}
               otherreas: []
               member: {}
               container: <AnalysisRequest at /senaite/clients/client-6/24-533a-0069>
               user: <PropertiedUser 'admin'>
               portal_url: <URLTool at /senaite/portal_url used for /senaite/clients/client-6/24-533a-0069>
               traverse_subpath: []
               template: <Products.Five.browser.pagetemplatefile.ViewPageTemplateFile object at 0x11e7d1790>
               translate: <function translate at 0x11e67c1d0>
               authorizers: [{'phone': '(207) 315 2567 x 317', 'department': 'PFAS Analysis', 'uid': u'3fbf90a4a73141a286e108f1257eb517', 'signature': 'http://localhost:8080/senaite/bika_setup/bika_labcontacts/labcontact-1/Signature', 'salutation': 'Dr', 'fullname': 'Christoph Aeppli', 'email': 'caeppli@bigelow.org', 'job_title': 'Manager/Technical Director'}]
               views: <Products.Five.browser.pagetemplatefile.ViewMapper object at 0x11e669190>
               args: ()
               lab: <Laboratory at /senaite/bika_setup/laboratory>
               portal: <PloneSite at /senaite>
               here: <AnalysisRequest at /senaite/clients/client-6/24-533a-0069>
               nothing: None
               repeat: <Products.PageTemplates.engine.RepeatDictWrapper object at 0x11fa33d20>
               default: <DEFAULT>
               request: <WSGIRequest, URL=http://localhost:8080/senaite/samples/reject_samples>
               client: <Client at /senaite/clients/client-6>
               context: <AnalysisRequest at /senaite/clients/client-6/24-533a-0069>
               portal_state: <Products.Five.browser.metaconfigure.PortalState object at 0x11dc22050>
               target_language: None
               root: <Application at >
               options: {}
               loop: {u'line': <Products.PageTemplates.engine.RepeatItem object at 0x11dc03f10>, u'reason': <Products.PageTemplates.engine.RepeatItem object at 0x11db23b90>}
               view: <senaite.core.browser.samples.rejection.report.RejectionReport object at 0x11d8e2090>
```

Probably easiest if you return a default dictionary with the all the required keys set to `None` here. Otherwise you need to handle it in the template with `python:member.get('signature', '-')`

https://github.com/senaite/senaite.core/blob/10665090ee8493603c97b02cbac5a186db6e3f41/src/senaite/core/browser/samples/rejection/report.py#L127-L128

**Comment by xispa** [comment]
> Hi Jordi, I'm getting this traceback when rejecting as `admin` user (i.e. a no `contact`/`labcontact` linked user)

Apologies :sweat_smile: , it should be ok now

**Comment by ramonski** [comment]
Hi Jordi,

It seems like we're missing a proper notification when no valid recipient emails are set for the sample, so that simply no email is sent out, although the notification checkbox was clicked:

```python
 545     def do_rejection(sample, notify=None):
 546         """Rejects the sample and if succeeds, generates the rejection pdf and
 547         sends a notification email. If notify is None, the notification email will
 548         only be sent if the setting in Setup is enabled
 549         """
 550         sample_id = api.get_id(sample)
 551         if not sample.getRejectionReasons():
 552             logger.warn("Cannot reject {} w/o rejection reasons".format(sample_id))
 553             return
 554
 555         success, msg = doActionFor(sample, "reject")
 556         if not success:
 557             logger.warn("Cannot reject the sample {}".format(sample_id))
 558             return
 559
 560         # Generate a pdf with the rejection reasons
 561         pdf = get_rejection_pdf(sample)
 562
 563         # Attach the PDF to the sample
 564         filename = "{}-rejected.pdf".format(sample_id)
 565         attachment = sample.createAttachment(pdf, filename=filename)
 566         pdf_file = attachment.getAttachmentFile()
 567
 568         # Do we need to send a notification email?
 569         if notify is None:
 570             setup = api.get_setup()
 571             notify = setup.getNotifyOnSampleRejection()
 572
 573         if notify:
 574             # Compose and send the email
 575  ->         mime_msg = get_rejection_mail(sample, pdf_file)
 576             if mime_msg:
 577                 # Send the email
 578                 send_email(mime_msg)
(Pdb++) sample
<AnalysisRequest at /senaite/clients/client-6/24-533a-0062>
(Pdb++) notify
True
(Pdb++) len(pdf)
53476
(Pdb++) get_rejection_mail(sample, pdf_file)
2024-07-20 09:03:34,508 WARNING [senaite.core:628][waitress-1] No valid recipients for 24-533a-0062
(Pdb++)
```

Let me think what you think about handling it about handling this.

Maybe we disable the "Send Email notification" checkbox if no valid recipients were found in the sample and put a notification below about the reason?

**Comment by xispa** [comment]
> Maybe we disable the "Send Email notification" checkbox if no valid recipients were found in the sample and put a notification below about the reason?

Addressed with https://github.com/senaite/senaite.core/pull/2589/commits/bb8c389c2c62e5ccc4cc9c6f34969c2af84a1261

**Review by ramonski — APPROVED** [review]
Cool, thanks!

**Pull request merged**
