### PR TITLE
User defined list for units in analysis services

### PR DESCRIPTION
**Pull request by RML-IAEA**
## Description of the issue/feature this PR addresses
This feature updates the analysis service units form a predefined list. The list is defined using the result variables and specific keyword, "units". When saving data for an analysis the user can select the units which updates the unit variable for the analysis service. 

## Current behavior before PR
Unable to change the units for an analysis service 

## Desired behavior after PR is merged
Able to manage the units for an analysis service with a predefined list of units. 
--
I confirm I have tested this PR thoroughly and coded it according to [PEP8][1]
and [Plone's Python styleguide][2] standards.

[1]: https://www.python.org/dev/peps/pep-0008
[2]: https://docs.plone.org/develop/styleguide/python.html

### CODE REVIEW

**Review by xispa — CHANGES_REQUESTED** [review]
Thanks for your contribution @LimsIAEA, I think the idea of allowing the manual input of Unit is really cool, but I feel this should be done differently.

> This feature updates the analysis service units form a predefined list. The list is defined using the result variables and specific keyword, "units". [...]

The part where you define the result options for an interim with name "unit" is not here. So no selection list will be rendered when an interim field with name "unit" is defined for a given analysis/service. Also note this "unit" interim field needs to be added manually by the user for this functionality to happen, which means that either the user realized about this functionality by chance or because read this PR at some point and found it of interest.

From a technical perspective I think it would be a lot simpler by making the field "Unit" editable in analyses view, as we already do for some fields if necessary, like for Uncertainty: https://github.com/senaite/senaite.core/blob/33a18ac3be39c06e1d21d2cf2b6e085872e12896/src/bika/lims/browser/analyses/view.py#L1175-L1179.

Therefore, I suggest first to not use interim fields, but add a bool field "[ ] Allow manual input of unit" at service level (as we have for uncertainty and detection limit). And when checked, make the field "Unit" editable in analyses listing. You can add another field forr "unit options" afterwards, that you will use to populate a selection list instead of a plain input field in the listing.

**Comment by RML-IAEA** [comment]
Thank you Jordi. I will implement your recommendations. It is taking a long time as I need to reload the environment after each change. Please can you advice on how to reload the Senaite Environment after changes to '.py' files?


So far in my Docker environment I am have included sauna.reload. The reload works for me the first time and then fails. I've tried everything that is detailed in https://pypi.org/project/sauna.reload/. How are you and others reloading the Senaite Environment? Thank you for all your help.

**Comment by ramonski** [comment]
> Thank you Jordi. I will implement your recommendations. It is taking a long time as I need to reload the environment after each change. Please can you advice on how to reload the Senaite Environment after changes to '.py' files?
> 
> So far in my Docker environment I am have included sauna.reload. The reload works for me the first time and then fails. I've tried everything that is detailed in https://pypi.org/project/sauna.reload/. How are you and others reloading the Senaite Environment? Thank you for all your help.

The `sauna.reload` package did not have an update since [2016-02-24](https://pypi.org/project/sauna.reload/#toc-entry-27). Please use [plone.reload](https://pypi.org/project/plone.reload) instead

**Comment by RML-IAEA** [comment]
Thank you @ramonski and @xispa for the advice. I have implemented a feature that will allow for a list of units to be defined for an analysis service. Units can then be selected from this list when submitting data.

**Comment by RML-IAEA** [comment]
Multiple units are defined in the analysis service: 
image

The user can then select a unit at data entry;
image
image
image

**Pull request closed without merging**
